/* CONTRATS */
export const GET_CONTRATS = "GET_CONTRATS"
export const GET_CONTRAT = "GET_CONTRAT"
export const GET_CONTRATS_SUCCESS = "GET_CONTRATS_SUCCESS"
export const GET_CONTRAT_SUCCESS = "GET_CONTRAT_SUCCESS"

export const GET_CONTRATS_FAIL = "GET_CONTRATS_FAIL"
export const ADD_NEW_CONTRAT="ADD_NEW_CONTRAT"
export const ADD_CONTRAT_SUCCESS = "ADD_CONTRAT_SUCCESS"
export const ADD_CONTRAT_FAIL = "ADD_CONTRAT_FAIL"

export const UPDATE_CONTRAT ="UPDATE_CONTRAT"
export const UPDATE_CONTRAT_SUCCESS ="UPDATE_CONTRAT_SUCCESS"
export const UPDATE_CONTRAT_FAIL = "UPDATE_CONTRAT_FAIL"

export const DELETE_CONTRAT = "DELETE_CONTRAT"
export const DELETE_CONTRAT_SUCCESS = "DELETE_CONTRAT_SUCCESS"
export const DELETE_CONTRAT_FAIL = "DELETE_CONTRAT_FAIL"