/* ENTREPRISES */
export const GET_ENTREPRISES = "GET_ENTREPRISES"
export const GET_ENTREPRISE = "GET_ENTREPRISE"
export const GET_ENTREPRISES_SUCCESS = "GET_ENTREPRISES_SUCCESS"
export const GET_ENTREPRISE_SUCCESS = "GET_ENTREPRISE_SUCCESS"

export const GET_ENTREPRISES_FAIL = "GET_ENTREPRISES_FAIL"
export const ADD_NEW_ENTREPRISE="ADD_NEW_ENTREPRISE"
export const ADD_ENTREPRISE_SUCCESS = "ADD_ENTREPRISE_SUCCESS"
export const ADD_ENTREPRISE_FAIL = "ADD_ENTREPRISE_FAIL"

export const UPDATE_ENTREPRISE ="UPDATE_ENTREPRISE"
export const UPDATE_ENTREPRISE_SUCCESS ="UPDATE_ENTREPRISE_SUCCESS"
export const UPDATE_ENTREPRISE_FAIL = "UPDATE_ENTREPRISE_FAIL"

export const DELETE_ENTREPRISE = "DELETE_ENTREPRISE"
export const DELETE_ENTREPRISE_SUCCESS = "DELETE_ENTREPRISE_SUCCESS"
export const DELETE_ENTREPRISE_FAIL = "DELETE_ENTREPRISE_FAIL"