/* TARIFS */
export const GET_TARIFS = "GET_TARIFS"
export const GET_TARIF = "GET_TARIF"
export const GET_TARIFS_SUCCESS = "GET_TARIFS_SUCCESS"
export const GET_TARIF_SUCCESS = "GET_TARIF_SUCCESS"

export const GET_TARIFS_FAIL = "GET_TARIFS_FAIL"
export const ADD_NEW_TARIF="ADD_NEW_TARIF"
export const ADD_TARIF_SUCCESS = "ADD_TARIF_SUCCESS"
export const ADD_TARIF_FAIL = "ADD_TARIF_FAIL"

export const UPDATE_TARIF ="UPDATE_TARIF"
export const UPDATE_TARIF_SUCCESS ="UPDATE_TARIF_SUCCESS"
export const UPDATE_TARIF_FAIL = "UPDATE_TARIF_FAIL"

export const DELETE_TARIF = "DELETE_TARIF"
export const DELETE_TARIF_SUCCESS = "DELETE_TARIF_SUCCESS"
export const DELETE_TARIF_FAIL = "DELETE_TARIF_FAIL"