<?php

namespace ContainerOwZZ7RJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WGZMakrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WGZMakr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WGZMakr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chantierRepository' => ['privates', 'App\\Repository\\ChantierRepository', 'getChantierRepositoryService', true],
            'entrepriseRepository' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
            'paysRepository' => ['privates', 'App\\Repository\\PaysRepository', 'getPaysRepositoryService', true],
            'personneRepository' => ['privates', 'App\\Repository\\PersonneRepository', 'getPersonneRepositoryService', true],
            'qualificationRepository' => ['privates', 'App\\Repository\\QualificationRepository', 'getQualificationRepositoryService', true],
        ], [
            'chantierRepository' => 'App\\Repository\\ChantierRepository',
            'entrepriseRepository' => 'App\\Repository\\EntrepriseRepository',
            'paysRepository' => 'App\\Repository\\PaysRepository',
            'personneRepository' => 'App\\Repository\\PersonneRepository',
            'qualificationRepository' => 'App\\Repository\\QualificationRepository',
        ]);
    }
}
