<?php

namespace ContainerOwZZ7RJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBanque2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.P81a8.X.App\Entity\Banque' shared service.
     *
     * @return \App\Entity\Banque
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.P81a8.X": it references class "App\\Entity\\Banque" but no such service exists.');
    }
}
