/* EXOBJETS */
export const GET_EXOBJETS = "GET_EXOBJETS"
export const GET_EXOBJETS_SUCCESS = "GET_EXOBJETS_SUCCESS"
export const GET_EXOBJETS_FAIL = "GET_EXOBJETS_FAIL"
export const ADD_NEW_EXOBJET="ADD_NEW_EXOBJET"
export const ADD_EXOBJET_SUCCESS = "ADD_EXOBJET_SUCCESS"
export const ADD_EXOBJET_FAIL = "ADD_EXOBJET_FAIL"

export const UPDATE_EXOBJET ="UPDATE_EXOBJET"
export const UPDATE_EXOBJET_SUCCESS ="UPDATE_EXOBJET_SUCCESS"
export const UPDATE_EXOBJET_FAIL = "UPDATE_EXOBJET_FAIL"

export const DELETE_EXOBJET = "DELETE_EXOBJET"
export const DELETE_EXOBJET_SUCCESS = "DELETE_EXOBJET_SUCCESS"
export const DELETE_EXOBJET_FAIL = "DELETE_EXOBJET_FAIL"