/* CERTIFICATS */
export const GET_CERTIFICATS = "GET_CERTIFICATS"
export const GET_CERTIFICATS_SUCCESS = "GET_CERTIFICATS_SUCCESS"
export const GET_CERTIFICATS_FAIL = "GET_CERTIFICATS_FAIL"
export const ADD_NEW_CERTIFICAT="ADD_NEW_CERTIFICAT"
export const ADD_CERTIFICAT_SUCCESS = "ADD_CERTIFICAT_SUCCESS"
export const ADD_CERTIFICAT_FAIL = "ADD_CERTIFICAT_FAIL"

export const UPDATE_CERTIFICAT ="UPDATE_CERTIFICAT"
export const UPDATE_CERTIFICAT_SUCCESS ="UPDATE_CERTIFICAT_SUCCESS"
export const UPDATE_CERTIFICAT_FAIL = "UPDATE_CERTIFICAT_FAIL"

export const DELETE_CERTIFICAT = "DELETE_CERTIFICAT"
export const DELETE_CERTIFICAT_SUCCESS = "DELETE_CERTIFICAT_SUCCESS"
export const DELETE_CERTIFICAT_FAIL = "DELETE_CERTIFICAT_FAIL"