/* GROUPES */
export const GET_GROUPES = "GET_GROUPES"
export const GET_GROUPES_SUCCESS = "GET_GROUPES_SUCCESS"
export const GET_GROUPES_FAIL = "GET_GROUPES_FAIL"
export const ADD_NEW_GROUPE="ADD_NEW_GROUPE"
export const ADD_GROUPE_SUCCESS = "ADD_GROUPE_SUCCESS"
export const ADD_GROUPE_FAIL = "ADD_GROUPE_FAIL"

export const UPDATE_GROUPE ="UPDATE_GROUPE"
export const UPDATE_GROUPE_SUCCESS ="UPDATE_GROUPE_SUCCESS"
export const UPDATE_GROUPE_FAIL = "UPDATE_GROUPE_FAIL"

export const DELETE_GROUPE = "DELETE_GROUPE"
export const DELETE_GROUPE_SUCCESS = "DELETE_GROUPE_SUCCESS"
export const DELETE_GROUPE_FAIL = "DELETE_GROUPE_FAIL"