/* EXEVALUATIONS */
export const GET_EXEVALUATIONS = "GET_EXEVALUATIONS"
export const GET_EXEVALUATIONS_SUCCESS = "GET_EXEVALUATIONS_SUCCESS"
export const GET_EXEVALUATIONS_FAIL = "GET_EXEVALUATIONS_FAIL"
export const ADD_NEW_EXEVALUATION="ADD_NEW_EXEVALUATION"
export const ADD_EXEVALUATION_SUCCESS = "ADD_EXEVALUATION_SUCCESS"
export const ADD_EXEVALUATION_FAIL = "ADD_EXEVALUATION_FAIL"

export const UPDATE_EXEVALUATION ="UPDATE_EXEVALUATION"
export const UPDATE_EXEVALUATION_SUCCESS ="UPDATE_EXEVALUATION_SUCCESS"
export const UPDATE_EXEVALUATION_FAIL = "UPDATE_EXEVALUATION_FAIL"

export const DELETE_EXEVALUATION = "DELETE_EXEVALUATION"
export const DELETE_EXEVALUATION_SUCCESS = "DELETE_EXEVALUATION_SUCCESS"
export const DELETE_EXEVALUATION_FAIL = "DELETE_EXEVALUATION_FAIL"