/* PERSONNES */
export const GET_PERSONNES = "GET_PERSONNES"
export const GET_PERSONNES_SUCCESS = "GET_PERSONNES_SUCCESS"
export const GET_PERSONNES_FAIL = "GET_PERSONNES_FAIL"
export const GET_IPERSONNES = "GET_IPERSONNES"
export const GET_IPERSONNES_SUCCESS = "GET_IPERSONNES_SUCCESS"
export const GET_IPERSONNES_FAIL = "GET_IPERSONNES_FAIL"
export const ADD_NEW_PERSONNE="ADD_NEW_PERSONNE"
export const ADD_PERSONNE_SUCCESS = "ADD_PERSONNE_SUCCESS"
export const ADD_PERSONNE_FAIL = "ADD_PERSONNE_FAIL"

export const UPDATE_PERSONNE ="UPDATE_PERSONNE"
export const UPDATE_PERSONNE_SUCCESS ="UPDATE_PERSONNE_SUCCESS"
export const UPDATE_PERSONNE_FAIL = "UPDATE_PERSONNE_FAIL"

export const DELETE_PERSONNE = "DELETE_PERSONNE"
export const DELETE_PERSONNE_SUCCESS = "DELETE_PERSONNE_SUCCESS"
export const DELETE_PERSONNE_FAIL = "DELETE_PERSONNE_FAIL"