/* OBJETS */
export const GET_OBJETS = "GET_OBJETS"
export const GET_OBJETS_SUCCESS = "GET_OBJETS_SUCCESS"
export const GET_OBJETS_FAIL = "GET_OBJETS_FAIL"
export const ADD_NEW_OBJET="ADD_NEW_OBJET"
export const ADD_OBJET_SUCCESS = "ADD_OBJET_SUCCESS"
export const ADD_OBJET_FAIL = "ADD_OBJET_FAIL"

export const UPDATE_OBJET ="UPDATE_OBJET"
export const UPDATE_OBJET_SUCCESS ="UPDATE_OBJET_SUCCESS"
export const UPDATE_OBJET_FAIL = "UPDATE_OBJET_FAIL"

export const DELETE_OBJET = "DELETE_OBJET"
export const DELETE_OBJET_SUCCESS = "DELETE_OBJET_SUCCESS"
export const DELETE_OBJET_FAIL = "DELETE_OBJET_FAIL"