/* ACTIVITES */
export const GET_ACTIVITES = "GET_ACTIVITES"
export const GET_ACTIVITES_SUCCESS = "GET_ACTIVITES_SUCCESS"
export const GET_ACTIVITES_FAIL = "GET_ACTIVITES_FAIL"
export const ADD_NEW_ACTIVITE="ADD_NEW_ACTIVITE"
export const ADD_ACTIVITE_SUCCESS = "ADD_ACTIVITE_SUCCESS"
export const ADD_ACTIVITE_FAIL = "ADD_ACTIVITE_FAIL"

export const UPDATE_ACTIVITE ="UPDATE_ACTIVITE"
export const UPDATE_ACTIVITE_SUCCESS ="UPDATE_ACTIVITE_SUCCESS"
export const UPDATE_ACTIVITE_FAIL = "UPDATE_ACTIVITE_FAIL"

export const DELETE_ACTIVITE = "DELETE_ACTIVITE"
export const DELETE_ACTIVITE_SUCCESS = "DELETE_ACTIVITE_SUCCESS"
export const DELETE_ACTIVITE_FAIL = "DELETE_ACTIVITE_FAIL"