/* XPERSONNES */
export const GET_XPERSONNES = "GET_XPERSONNES"
export const GET_XPERSONNES_SUCCESS = "GET_XPERSONNES_SUCCESS"
export const GET_XPERSONNES_FAIL = "GET_XPERSONNES_FAIL"
export const ADD_NEW_XPERSONNE="ADD_NEW_XPERSONNE"
export const ADD_XPERSONNE_SUCCESS = "ADD_XPERSONNE_SUCCESS"
export const ADD_XPERSONNE_FAIL = "ADD_XPERSONNE_FAIL"

export const UPDATE_XPERSONNE ="UPDATE_XPERSONNE"
export const UPDATE_XPERSONNE_SUCCESS ="UPDATE_XPERSONNE_SUCCESS"
export const UPDATE_XPERSONNE_FAIL = "UPDATE_XPERSONNE_FAIL"

export const DELETE_XPERSONNE = "DELETE_XPERSONNE"
export const DELETE_XPERSONNE_SUCCESS = "DELETE_XPERSONNE_SUCCESS"
export const DELETE_XPERSONNE_FAIL = "DELETE_XPERSONNE_FAIL"