/* EXREMARQUES */
export const GET_EXREMARQUES = "GET_EXREMARQUES"
export const GET_EXREMARQUES_SUCCESS = "GET_EXREMARQUES_SUCCESS"
export const GET_EXREMARQUES_FAIL = "GET_EXREMARQUES_FAIL"
export const ADD_NEW_EXREMARQUE="ADD_NEW_EXREMARQUE"
export const ADD_EXREMARQUE_SUCCESS = "ADD_EXREMARQUE_SUCCESS"
export const ADD_EXREMARQUE_FAIL = "ADD_EXREMARQUE_FAIL"

export const UPDATE_EXREMARQUE ="UPDATE_EXREMARQUE"
export const UPDATE_EXREMARQUE_SUCCESS ="UPDATE_EXREMARQUE_SUCCESS"
export const UPDATE_EXREMARQUE_FAIL = "UPDATE_EXREMARQUE_FAIL"

export const DELETE_EXREMARQUE = "DELETE_EXREMARQUE"
export const DELETE_EXREMARQUE_SUCCESS = "DELETE_EXREMARQUE_SUCCESS"
export const DELETE_EXREMARQUE_FAIL = "DELETE_EXREMARQUE_FAIL"