/* SMARTPHONES */
export const GET_SMARTPHONES = "GET_SMARTPHONES"
export const GET_SMARTPHONE = "GET_SMARTPHONE"
export const GET_SMARTPHONES_SUCCESS = "GET_SMARTPHONES_SUCCESS"
export const GET_SMARTPHONE_SUCCESS = "GET_SMARTPHONE_SUCCESS"

export const GET_SMARTPHONES_FAIL = "GET_SMARTPHONES_FAIL"
export const ADD_NEW_SMARTPHONE="ADD_NEW_SMARTPHONE"
export const ADD_SMARTPHONE_SUCCESS = "ADD_SMARTPHONE_SUCCESS"
export const ADD_SMARTPHONE_FAIL = "ADD_SMARTPHONE_FAIL"

export const UPDATE_SMARTPHONE ="UPDATE_SMARTPHONE"
export const UPDATE_SMARTPHONE_SUCCESS ="UPDATE_SMARTPHONE_SUCCESS"
export const UPDATE_SMARTPHONE_FAIL = "UPDATE_SMARTPHONE_FAIL"

export const DELETE_SMARTPHONE = "DELETE_SMARTPHONE"
export const DELETE_SMARTPHONE_SUCCESS = "DELETE_SMARTPHONE_SUCCESS"
export const DELETE_SMARTPHONE_FAIL = "DELETE_SMARTPHONE_FAIL"