/* INOBJETS */
export const GET_INOBJETS = "GET_INOBJETS"
export const GET_INOBJETS_SUCCESS = "GET_INOBJETS_SUCCESS"
export const GET_INOBJETS_FAIL = "GET_INOBJETS_FAIL"
export const ADD_NEW_INOBJET="ADD_NEW_INOBJET"
export const ADD_INOBJET_SUCCESS = "ADD_INOBJET_SUCCESS"
export const ADD_INOBJET_FAIL = "ADD_INOBJET_FAIL"

export const UPDATE_INOBJET ="UPDATE_INOBJET"
export const UPDATE_INOBJET_SUCCESS ="UPDATE_INOBJET_SUCCESS"
export const UPDATE_INOBJET_FAIL = "UPDATE_INOBJET_FAIL"

export const DELETE_INOBJET = "DELETE_INOBJET"
export const DELETE_INOBJET_SUCCESS = "DELETE_INOBJET_SUCCESS"
export const DELETE_INOBJET_FAIL = "DELETE_INOBJET_FAIL"