/* LISTACTIVITES */
export const GET_LISTACTIVITES = "GET_LISTACTIVITES"
export const GET_LISTACTIVITES_SUCCESS = "GET_LISTACTIVITES_SUCCESS"
export const GET_LISTACTIVITES_FAIL = "GET_LISTACTIVITES_FAIL"
export const ADD_NEW_LISTACTIVITE="ADD_NEW_LISTACTIVITE"
export const ADD_LISTACTIVITE_SUCCESS = "ADD_LISTACTIVITE_SUCCESS"
export const ADD_LISTACTIVITE_FAIL = "ADD_LISTACTIVITE_FAIL"

export const UPDATE_LISTACTIVITE ="UPDATE_LISTACTIVITE"
export const UPDATE_LISTACTIVITE_SUCCESS ="UPDATE_LISTACTIVITE_SUCCESS"
export const UPDATE_LISTACTIVITE_FAIL = "UPDATE_LISTACTIVITE_FAIL"

export const DELETE_LISTACTIVITE = "DELETE_LISTACTIVITE"
export const DELETE_LISTACTIVITE_SUCCESS = "DELETE_LISTACTIVITE_SUCCESS"
export const DELETE_LISTACTIVITE_FAIL = "DELETE_LISTACTIVITE_FAIL"