/* INEVALUATIONS */
export const GET_INEVALUATIONS = "GET_INEVALUATIONS"
export const GET_INEVALUATIONS_SUCCESS = "GET_INEVALUATIONS_SUCCESS"
export const GET_INEVALUATIONS_FAIL = "GET_INEVALUATIONS_FAIL"
export const ADD_NEW_INEVALUATION="ADD_NEW_INEVALUATION"
export const ADD_INEVALUATION_SUCCESS = "ADD_INEVALUATION_SUCCESS"
export const ADD_INEVALUATION_FAIL = "ADD_INEVALUATION_FAIL"

export const UPDATE_INEVALUATION ="UPDATE_INEVALUATION"
export const UPDATE_INEVALUATION_SUCCESS ="UPDATE_INEVALUATION_SUCCESS"
export const UPDATE_INEVALUATION_FAIL = "UPDATE_INEVALUATION_FAIL"

export const DELETE_INEVALUATION = "DELETE_INEVALUATION"
export const DELETE_INEVALUATION_SUCCESS = "DELETE_INEVALUATION_SUCCESS"
export const DELETE_INEVALUATION_FAIL = "DELETE_INEVALUATION_FAIL"