/* INREMARQUES */
export const GET_INREMARQUES = "GET_INREMARQUES"
export const GET_INREMARQUES_SUCCESS = "GET_INREMARQUES_SUCCESS"
export const GET_INREMARQUES_FAIL = "GET_INREMARQUES_FAIL"
export const ADD_NEW_INREMARQUE="ADD_NEW_INREMARQUE"
export const ADD_INREMARQUE_SUCCESS = "ADD_INREMARQUE_SUCCESS"
export const ADD_INREMARQUE_FAIL = "ADD_INREMARQUE_FAIL"

export const UPDATE_INREMARQUE ="UPDATE_INREMARQUE"
export const UPDATE_INREMARQUE_SUCCESS ="UPDATE_INREMARQUE_SUCCESS"
export const UPDATE_INREMARQUE_FAIL = "UPDATE_INREMARQUE_FAIL"

export const DELETE_INREMARQUE = "DELETE_INREMARQUE"
export const DELETE_INREMARQUE_SUCCESS = "DELETE_INREMARQUE_SUCCESS"
export const DELETE_INREMARQUE_FAIL = "DELETE_INREMARQUE_FAIL"