/* BANQUES */
export const GET_BANQUES = "GET_BANQUES"
export const GET_BANQUES_SUCCESS = "GET_BANQUES_SUCCESS"
export const GET_BANQUES_FAIL = "GET_BANQUES_FAIL"
export const ADD_NEW_BANQUE="ADD_NEW_BANQUE"
export const ADD_BANQUE_SUCCESS = "ADD_BANQUE_SUCCESS"
export const ADD_BANQUE_FAIL = "ADD_BANQUE_FAIL"

export const UPDATE_BANQUE ="UPDATE_BANQUE"
export const UPDATE_BANQUE_SUCCESS ="UPDATE_BANQUE_SUCCESS"
export const UPDATE_BANQUE_FAIL = "UPDATE_BANQUE_FAIL"

export const DELETE_BANQUE = "DELETE_BANQUE"
export const DELETE_BANQUE_SUCCESS = "DELETE_BANQUE_SUCCESS"
export const DELETE_BANQUE_FAIL = "DELETE_BANQUE_FAIL"