/* CHANTIERS */
export const GET_CHANTIERS = "GET_CHANTIERS"
export const GET_CHANTIER = "GET_CHANTIER"
export const GET_CHANTIERS_SUCCESS = "GET_CHANTIERS_SUCCESS"
export const GET_CHANTIER_SUCCESS = "GET_CHANTIER_SUCCESS"

export const GET_CHANTIERS_FAIL = "GET_CHANTIERS_FAIL"
export const ADD_NEW_CHANTIER="ADD_NEW_CHANTIER"
export const ADD_CHANTIER_SUCCESS = "ADD_CHANTIER_SUCCESS"
export const ADD_CHANTIER_FAIL = "ADD_CHANTIER_FAIL"

export const UPDATE_CHANTIER ="UPDATE_CHANTIER"
export const UPDATE_CHANTIER_SUCCESS ="UPDATE_CHANTIER_SUCCESS"
export const UPDATE_CHANTIER_FAIL = "UPDATE_CHANTIER_FAIL"

export const DELETE_CHANTIER = "DELETE_CHANTIER"
export const DELETE_CHANTIER_SUCCESS = "DELETE_CHANTIER_SUCCESS"
export const DELETE_CHANTIER_FAIL = "DELETE_CHANTIER_FAIL"