<?php

namespace ContainerRGPxbl9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0fiQlh0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0fiQlh0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0fiQlh0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'personne' => ['privates', '.errored..service_locator.0fiQlh0.App\\Entity\\Personne', NULL, 'Cannot autowire service ".service_locator.0fiQlh0": it references class "App\\Entity\\Personne" but no such service exists.'],
        ], [
            'personne' => 'App\\Entity\\Personne',
        ]);
    }
}
