<?php

namespace ContainerRGPxbl9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B3KMaTDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b3KMaTD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b3KMaTD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['privates', '.errored.nOVf.2z', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::add()": the $encoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordEncoderInterface". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.lXa.CoN', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::add()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'encoder' => '?',
            'request' => '?',
        ]);
    }
}
