/* QUALIFICATIONS */
export const GET_QUALIFICATIONS = "GET_QUALIFICATIONS"
export const GET_QUALIFICATIONS_SUCCESS = "GET_QUALIFICATIONS_SUCCESS"
export const GET_QUALIFICATIONS_FAIL = "GET_QUALIFICATIONS_FAIL"
export const ADD_NEW_QUALIFICATION="ADD_NEW_QUALIFICATION"
export const ADD_QUALIFICATION_SUCCESS = "ADD_QUALIFICATION_SUCCESS"
export const ADD_QUALIFICATION_FAIL = "ADD_QUALIFICATION_FAIL"

export const UPDATE_QUALIFICATION ="UPDATE_QUALIFICATION"
export const UPDATE_QUALIFICATION_SUCCESS ="UPDATE_QUALIFICATION_SUCCESS"
export const UPDATE_QUALIFICATION_FAIL = "UPDATE_QUALIFICATION_FAIL"

export const DELETE_QUALIFICATION = "DELETE_QUALIFICATION"
export const DELETE_QUALIFICATION_SUCCESS = "DELETE_QUALIFICATION_SUCCESS"
export const DELETE_QUALIFICATION_FAIL = "DELETE_QUALIFICATION_FAIL"