/* PERSONNELS */
export const GET_PERSONNELS = "GET_PERSONNELS"
export const GET_PERSONNELS_SUCCESS = "GET_PERSONNELS_SUCCESS"
export const GET_PERSONNELS_FAIL = "GET_PERSONNELS_FAIL"
export const ADD_NEW_PERSONNEL="ADD_NEW_PERSONNEL"
export const ADD_PERSONNEL_SUCCESS = "ADD_PERSONNEL_SUCCESS"
export const ADD_PERSONNEL_FAIL = "ADD_PERSONNEL_FAIL"

export const UPDATE_PERSONNEL ="UPDATE_PERSONNEL"
export const UPDATE_PERSONNEL_SUCCESS ="UPDATE_PERSONNEL_SUCCESS"
export const UPDATE_PERSONNEL_FAIL = "UPDATE_PERSONNEL_FAIL"

export const DELETE_PERSONNEL = "DELETE_PERSONNEL"
export const DELETE_PERSONNEL_SUCCESS = "DELETE_PERSONNEL_SUCCESS"
export const DELETE_PERSONNEL_FAIL = "DELETE_PERSONNEL_FAIL"