<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \App\Entity\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'actif', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'genre', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'dateDeNaissance', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'ncin', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'validateCin', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'idBadge', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'nmobile', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'numeroMaison', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'codePostale', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'remarque', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'profile', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'taux', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'heuresMax', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'formationSecurite', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'validiteFormationSecurite', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'autoriseesEvaluation', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'valeur', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'qualification', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'certification', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'contrats', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'objetRemis', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'presences', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'pointages', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'absences', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'image'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'actif', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'genre', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'dateDeNaissance', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'ncin', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'validateCin', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'idBadge', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'nmobile', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'numeroMaison', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'codePostale', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'remarque', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'profile', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'taux', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'heuresMax', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'formationSecurite', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'validiteFormationSecurite', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'autoriseesEvaluation', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'valeur', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'qualification', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'certification', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'contrats', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'objetRemis', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'presences', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'pointages', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'absences', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'image'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function isActif(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActif', []);

        return parent::isActif();
    }

    /**
     * {@inheritDoc}
     */
    public function setActif(?bool $actif): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActif', [$actif]);

        return parent::setActif($actif);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', []);

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre(?string $genre): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', [$genre]);

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', []);

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance(?\DateTimeInterface $dateDeNaissance): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', [$dateDeNaissance]);

        return parent::setDateDeNaissance($dateDeNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNcin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNcin', []);

        return parent::getNcin();
    }

    /**
     * {@inheritDoc}
     */
    public function setNcin(?string $ncin): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNcin', [$ncin]);

        return parent::setNcin($ncin);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidateCin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidateCin', []);

        return parent::getValidateCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidateCin(?\DateTimeInterface $validateCin): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidateCin', [$validateCin]);

        return parent::setValidateCin($validateCin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdBadge(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBadge', []);

        return parent::getIdBadge();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdBadge(?string $idBadge): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdBadge', [$idBadge]);

        return parent::setIdBadge($idBadge);
    }

    /**
     * {@inheritDoc}
     */
    public function getNmobile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNmobile', []);

        return parent::getNmobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setNmobile(?string $nmobile): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNmobile', [$nmobile]);

        return parent::setNmobile($nmobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroMaison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroMaison', []);

        return parent::getNumeroMaison();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroMaison(?string $numeroMaison): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroMaison', [$numeroMaison]);

        return parent::setNumeroMaison($numeroMaison);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostale', []);

        return parent::getCodePostale();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostale(?string $codePostale): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostale', [$codePostale]);

        return parent::setCodePostale($codePostale);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(?string $ville): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(?string $pays): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemarque(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemarque', []);

        return parent::getRemarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemarque(?string $remarque): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemarque', [$remarque]);

        return parent::setRemarque($remarque);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile(?string $profile): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', [$profile]);

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaux(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaux', []);

        return parent::getTaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaux(?string $taux): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaux', [$taux]);

        return parent::setTaux($taux);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresMax(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresMax', []);

        return parent::getHeuresMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresMax(?string $heuresMax): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresMax', [$heuresMax]);

        return parent::setHeuresMax($heuresMax);
    }

    /**
     * {@inheritDoc}
     */
    public function isFormationSecurite(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFormationSecurite', []);

        return parent::isFormationSecurite();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormationSecurite(?bool $formationSecurite): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormationSecurite', [$formationSecurite]);

        return parent::setFormationSecurite($formationSecurite);
    }

    /**
     * {@inheritDoc}
     */
    public function getValiditeFormationSecurite(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValiditeFormationSecurite', []);

        return parent::getValiditeFormationSecurite();
    }

    /**
     * {@inheritDoc}
     */
    public function setValiditeFormationSecurite(?\DateTimeInterface $validiteFormationSecurite): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValiditeFormationSecurite', [$validiteFormationSecurite]);

        return parent::setValiditeFormationSecurite($validiteFormationSecurite);
    }

    /**
     * {@inheritDoc}
     */
    public function isAutoriseesEvaluation(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAutoriseesEvaluation', []);

        return parent::isAutoriseesEvaluation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoriseesEvaluation(?bool $autoriseesEvaluation): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoriseesEvaluation', [$autoriseesEvaluation]);

        return parent::setAutoriseesEvaluation($autoriseesEvaluation);
    }

    /**
     * {@inheritDoc}
     */
    public function getValeur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValeur', []);

        return parent::getValeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setValeur(?string $valeur): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValeur', [$valeur]);

        return parent::setValeur($valeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualification(): ?\App\Entity\Qualification
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualification', []);

        return parent::getQualification();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualification(?\App\Entity\Qualification $qualification): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualification', [$qualification]);

        return parent::setQualification($qualification);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertification(): ?\App\Entity\Certification
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertification', []);

        return parent::getCertification();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertification(?\App\Entity\Certification $certification): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertification', [$certification]);

        return parent::setCertification($certification);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrats(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrats', []);

        return parent::getContrats();
    }

    /**
     * {@inheritDoc}
     */
    public function addContrat(\App\Entity\Contrat $contrat): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContrat', [$contrat]);

        return parent::addContrat($contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContrat(\App\Entity\Contrat $contrat): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContrat', [$contrat]);

        return parent::removeContrat($contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetRemis(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetRemis', []);

        return parent::getObjetRemis();
    }

    /**
     * {@inheritDoc}
     */
    public function addObjetRemi(\App\Entity\ObjetRemis $objetRemi): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObjetRemi', [$objetRemi]);

        return parent::addObjetRemi($objetRemi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeObjetRemi(\App\Entity\ObjetRemis $objetRemi): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeObjetRemi', [$objetRemi]);

        return parent::removeObjetRemi($objetRemi);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getPresences(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresences', []);

        return parent::getPresences();
    }

    /**
     * {@inheritDoc}
     */
    public function addPresence(\App\Entity\Presence $presence): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPresence', [$presence]);

        return parent::addPresence($presence);
    }

    /**
     * {@inheritDoc}
     */
    public function removePresence(\App\Entity\Presence $presence): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePresence', [$presence]);

        return parent::removePresence($presence);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointages', []);

        return parent::getPointages();
    }

    /**
     * {@inheritDoc}
     */
    public function addPointage(\App\Entity\Pointage $pointage): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPointage', [$pointage]);

        return parent::addPointage($pointage);
    }

    /**
     * {@inheritDoc}
     */
    public function removePointage(\App\Entity\Pointage $pointage): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePointage', [$pointage]);

        return parent::removePointage($pointage);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsences(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsences', []);

        return parent::getAbsences();
    }

    /**
     * {@inheritDoc}
     */
    public function addAbsence(\App\Entity\Absence $absence): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAbsence', [$absence]);

        return parent::addAbsence($absence);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAbsence(\App\Entity\Absence $absence): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAbsence', [$absence]);

        return parent::removeAbsence($absence);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(?string $image): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

}
