<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contrat extends \App\Entity\Contrat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'actif', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateFin', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'taux', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'heuresMax', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prime1', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'valeur1', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prime2', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'valeur2', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prime3', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prime4', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'valeur3', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'valeur4', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'formationSecurite', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'validiteFormationSecurite', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'personneExterne', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'employeur', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'qualification', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'chantier', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'visit', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateVisit', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'validePar'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'actif', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateFin', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'taux', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'heuresMax', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prime1', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'valeur1', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prime2', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'valeur2', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prime3', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prime4', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'valeur3', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'valeur4', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'formationSecurite', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'validiteFormationSecurite', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'personneExterne', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'employeur', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'qualification', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'chantier', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'visit', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateVisit', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'validePar'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contrat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function isActif(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActif', []);

        return parent::isActif();
    }

    /**
     * {@inheritDoc}
     */
    public function setActif(?bool $actif): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActif', [$actif]);

        return parent::setActif($actif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut(?\DateTimeInterface $dateDebut): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$dateDebut]);

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin(?\DateTimeInterface $dateFin): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$dateFin]);

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaux(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaux', []);

        return parent::getTaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaux(?string $taux): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaux', [$taux]);

        return parent::setTaux($taux);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresMax(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresMax', []);

        return parent::getHeuresMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresMax(string $heuresMax): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresMax', [$heuresMax]);

        return parent::setHeuresMax($heuresMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrime1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrime1', []);

        return parent::getPrime1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrime1(?string $prime1): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrime1', [$prime1]);

        return parent::setPrime1($prime1);
    }

    /**
     * {@inheritDoc}
     */
    public function getValeur1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValeur1', []);

        return parent::getValeur1();
    }

    /**
     * {@inheritDoc}
     */
    public function setValeur1(?string $valeur1): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValeur1', [$valeur1]);

        return parent::setValeur1($valeur1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrime2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrime2', []);

        return parent::getPrime2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrime2(?string $prime2): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrime2', [$prime2]);

        return parent::setPrime2($prime2);
    }

    /**
     * {@inheritDoc}
     */
    public function getValeur2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValeur2', []);

        return parent::getValeur2();
    }

    /**
     * {@inheritDoc}
     */
    public function setValeur2(?string $valeur2): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValeur2', [$valeur2]);

        return parent::setValeur2($valeur2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrime3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrime3', []);

        return parent::getPrime3();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrime3(?string $prime3): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrime3', [$prime3]);

        return parent::setPrime3($prime3);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrime4(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrime4', []);

        return parent::getPrime4();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrime4(?string $prime4): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrime4', [$prime4]);

        return parent::setPrime4($prime4);
    }

    /**
     * {@inheritDoc}
     */
    public function getValeur3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValeur3', []);

        return parent::getValeur3();
    }

    /**
     * {@inheritDoc}
     */
    public function setValeur3(?string $valeur3): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValeur3', [$valeur3]);

        return parent::setValeur3($valeur3);
    }

    /**
     * {@inheritDoc}
     */
    public function getValeur4(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValeur4', []);

        return parent::getValeur4();
    }

    /**
     * {@inheritDoc}
     */
    public function setValeur4(?string $valeur4): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValeur4', [$valeur4]);

        return parent::setValeur4($valeur4);
    }

    /**
     * {@inheritDoc}
     */
    public function isFormationSecurite(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFormationSecurite', []);

        return parent::isFormationSecurite();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormationSecurite(?bool $formationSecurite): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormationSecurite', [$formationSecurite]);

        return parent::setFormationSecurite($formationSecurite);
    }

    /**
     * {@inheritDoc}
     */
    public function getValiditeFormationSecurite(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValiditeFormationSecurite', []);

        return parent::getValiditeFormationSecurite();
    }

    /**
     * {@inheritDoc}
     */
    public function setValiditeFormationSecurite(?\DateTimeInterface $validiteFormationSecurite): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValiditeFormationSecurite', [$validiteFormationSecurite]);

        return parent::setValiditeFormationSecurite($validiteFormationSecurite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonneExterne(): ?\App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonneExterne', []);

        return parent::getPersonneExterne();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonneExterne(?\App\Entity\Personne $personneExterne): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonneExterne', [$personneExterne]);

        return parent::setPersonneExterne($personneExterne);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeur(): ?\App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeur', []);

        return parent::getEmployeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeur(?\App\Entity\Entreprise $employeur): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeur', [$employeur]);

        return parent::setEmployeur($employeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualification(): ?\App\Entity\Qualification
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualification', []);

        return parent::getQualification();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualification(?\App\Entity\Qualification $qualification): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualification', [$qualification]);

        return parent::setQualification($qualification);
    }

    /**
     * {@inheritDoc}
     */
    public function getChantier(): ?\App\Entity\Chantier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChantier', []);

        return parent::getChantier();
    }

    /**
     * {@inheritDoc}
     */
    public function setChantier(?\App\Entity\Chantier $chantier): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChantier', [$chantier]);

        return parent::setChantier($chantier);
    }

    /**
     * {@inheritDoc}
     */
    public function isStatut(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStatut', []);

        return parent::isStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(?bool $statut): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function isVisit(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisit', []);

        return parent::isVisit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisit(bool $visit): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisit', [$visit]);

        return parent::setVisit($visit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateVisit(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateVisit', []);

        return parent::getDateVisit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateVisit(\DateTimeInterface $dateVisit): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateVisit', [$dateVisit]);

        return parent::setDateVisit($dateVisit);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidePar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidePar', []);

        return parent::getValidePar();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidePar(?string $validePar): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidePar', [$validePar]);

        return parent::setValidePar($validePar);
    }

}
